# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0134_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='add_bot_by_user_permissions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
